brick_categories = [
    "Animal",
    "Antenna",
    "Arch",
    "Arm",
    "Bar",
    "Baseplate",
    "Belville",
    "Boat",
    "Bracket",
    "Brick",
    "Car",
    "Clikits",
    "Cockpit",
    "Cone",
    "Constraction",
    "Constraction Accessory",
    "Container",
    "Conveyor",
    "Crane",
    "Cylinder",
    "Dish",
    "Door",
    "Duplo",
    "Electric",
    "Exhaust",
    "Fence",
    "Figure",
    "Figure Accessory",
    "Flag",
    "Forklift",
    "Freestyle",
    "Garage",
    "Glass",
    "Grab",
    "Helper",
    "Hinge",
    "Homemaker",
    "Hose",
    "Ladder",
    "Lever",
    "Magnet",
    "Minifig",
    "Minifig Accessory",
    "Minifig Footwear",
    "Minifig Headwear",
    "Minifig Hipwear",
    "Minifig Neckwear",
    "Monorail",
    "Panel",
    "Plane",
    "Plant",
    "Plate",
    "Platform",
    "Propeller",
    "Rack",
    "Roadsign",
    "Rock",
    "Scala",
    "Screw",
    "Sheet Cardboard",
    "Sheet Fabric",
    "Sheet Plastic",
    "Slope",
    "Sphere",
    "Staircase",
    "Sticker",
    "String",
    "Support",
    "Tail",
    "Tap",
    "Technic",
    "Tile",
    "Tipper",
    "Tractor",
    "Trailer",
    "Train",
    "Turntable",
    "Tyre",
    "Vehicle",
    "Wedge",
    "Wheel",
    "Winch",
    "Window",
    "Windscreen",
    "Wing",
    "Znap",
]
