colour_categories = [
    "LDraw:LDraw Solid Colours",
    "LDraw:LDraw Transparent Colours",
    "LDraw:LDraw Chrome Plated Colours",
    "LDraw:LDraw Pearlescent Plastic Colours",
    "LDraw:LDraw Metallic Paint Colours",
    "LDraw:LDraw Fluorescent Paint Colours",
    "LDraw:LDraw Milky Colours",
    "LDraw:LDraw Glitter Colours",
    "LDraw:LDraw Speckle Colours",
    "LDraw:LDraw Modulex Colours",
    "LDraw:LDraw Rubber Colours",
    "LDraw:LDraw Transparent Rubber Colours",
    "LDraw:LDraw Fabric Colours",
    "LDraw:LDraw Internal Common Material Colours",
    "Bricklink:Glow in Dark(Render Only)",
    "Bricklink:Glowing Neon(Render Only)",
    "Bricklink:Luminous(Render Only)",
    "Bricklink:Luminous Soft(Render Only)",
    "Bricklink:Translucent(Render Only)",
]
